version: '3.9'

services:
  db:
    image: mysql:8.0
    container_name: impresiones-mysql
    restart: no
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: impresiones
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_user
    ports:
      - "3306:3306"
    volumes:
      - mysql_impresiones_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d   # opcional pero Ãºtil
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_impresiones_data: